# docs available at http://docs.travis-ci.com/user/languages/php/
# example available at https://github.com/travis-ci/travis-ci-php-example
language: php

before_script:
  - composer self-update

env: GEOPHP_RUN_TESTS=1

cache:
  directories:
  - $HOME/.composer/cache/files

install:
  - composer install --prefer-dist --no-interaction
  # TODO Install geos library -- as a matrix test
  # TODO optionally set up a postgis database for testing

script: 
  - cd tests
  - GEOS_DISABLED=1 ../vendor/bin/phpunit
  - php test.php

# run tests on the following versions
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  fast_finish: false
